### ISSUE TITLE
Does not work with Angular CLI 11

### ISSUE THREAD

**Issue by jgosar** [georgebyte/rxjs-observable-store#11]
I'm not exactly sure what is wrong, but it looks like this library does not work with Angular CLI 11.

I created a new app with Angular CLI 11 (using `ng new`) and then i added this library using `npm install rxjs-observable-store --save`.
Then I imported the store using `import { Store } from "rxjs-observable-store";` in one of my TS files.

From this point onward, the app did not work at all and the command `ng serve` did not start the app, but also didn't produce any output.

I have prepared a minimal example that reproduces the bug (Simply a fresh Angular CLI app which uses`rxjs-observable-store`):
Check out https://github.com/jgosar/rxjs-store-angular-11
Go to folder `rxjs-store-angular-11\test-app`
Run `ng serve`.

You can see that nothing at all happens and no website starts on localhost:4200

Now if you cancel this command and go to `app.component.ts` and remove the line `import { Store } from "rxjs-observable-store";`, and run `ng serve` again, the app starts correctly, so the problem must have something to do with this library.

When I switched back to Angular CLI 10 the app worked again, so this looks like an incompatibility between Angular CLI 11 and rxjs-observable-store.

**Comment by georgebyte** [comment]
Thanks for the report. I'm looking into this but the fix doesn't look like it's gonna be easy.

Based on a quick triage I concluded the issue lies in Angular 11 upgrading to TypeScript version 4.x. Recursive type definitions used by `rxjs-observable-store` to provide autocompletion on deep state paths cause Angular CLI build times (TS compilation) to lenghten exponentially. That's why it appears as nothing is happening when running `ng serve` - build time is just that (unusably) long.

**Comment by klopsknoedel** [comment]
In a project we've noticed that upgrading to TS 4.2 is causing this issue. As long as you stick to TS 4.1.x you should be fine using Angular 11.
Anyway, it would be great to have TS 4.2 support.

**Comment by georgebyte** [comment]
@klopsknoedel Thank you for your input. Just to make sure I understand correctly, in your case the library `rxjs-observable-store` works correctly when paired with TS 4.1.x but breaks when upgrading TS to version 4.2.x?

**Comment by sahofmann** [comment]
Hi @georgebyte. Yes, sort of. But first I have to clarify that I made a mistake here. As we tested upgrading Angular I've updated to "the latest TS-Version" which I had in mind as I wrote my comment. But at this time TS 4.2 wasn't released yet. So I said "broken with TS 4.2 but works with TS 4.1". That's wrong. It should be "broken with TS 4.1 but should work with TS 4.0". Sorry for the confusion.

We're using Angular 10 and TS 4.0.x for several months now and had no issues at all with `rxjs-observable-store`. That said, it would be worth a try to test out Angular 11 with TS 4.0.x.
However. We've tried to upgrade our application to Angular 11 and all other dependencies with it. To keep the scenario simple I've upgraded a small library-project, which is used in our main-application, to Angular 11 and TS 4.1.x and it failed building with the following error:
```
✖ Compiling TypeScript sources through NGC
ERROR: node_modules/rxjs-observable-store/lib/esm/store.d.ts:18:484 - error TS2589: Type instantiation is excessively deep and possibly infinite.

18     patchState<P1 extends keyof Object.Path<S, []>, P2 extends keyof Object.Path<S, [P1]>, P3 extends keyof Object.Path<S, [P1, P2]>, P4 extends keyof Object.Path<S, [P1, P2, P3]>, P5 extends keyof Object.Path<S, [P1, P2, P3, P4]>, P6 extends keyof Object.Path<S, [P1, P2, P3, P4, P5]>, P7 extends keyof Object.Path<S, [P1, P2, P3, P4, P5, P6]>, P8 extends keyof Object.Path<S, [P1, P2, P3, P4, P5, P6, P7]>, P9 extends keyof Object.Path<S, [P1, P2, P3, P4, P5, P6, P7, P8]>>(value: Object.Path<S, [P1, P2, P3, P4, P5, P6, P7, P8, P9]>, part1: P1, part2: P2, part3: P3, part4: P4, part5: P5, part6: P6, part7: P7, part8: P8, part9: P9): void;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

As soon as I switch back to TS 4.0.x everything builds properly. So it seems you should be fine using Angular 11 with this TS Version. I also have to mention that I haven't proceeded any further and didn't upgraded/test our main application due to time constraints. So I don't know if `ng serve` will break with 4.0. But while building succeeds you should give it a try.

**Comment by klopsknoedel** [comment]
Hi @georgebyte. Yes, sort of. But first I have to clarify that I made a mistake here. As we tested upgrading Angular I've updated to "the latest TS-Version" which I had in mind as I wrote my comment. But at this time TS 4.2 wasn't released yet. So I said "broken with TS 4.2 but works with TS 4.1". That's wrong. It should be "broken with TS 4.1 but should work with TS 4.0". Sorry for the confusion.

We're using Angular 10 and TS 4.0.x for several months now and had no issues at all with `rxjs-observable-store`. That said, it would be worth a try to test out Angular 11 with TS 4.0.x.
However. We've tried to upgrade our application to Angular 11 and all other dependencies with it. To keep the scenario simple I've upgraded a small library-project, which is used in our main-application, to Angular 11 and TS 4.1.x and it failed building with the following error:
```
✖ Compiling TypeScript sources through NGC
ERROR: node_modules/rxjs-observable-store/lib/esm/store.d.ts:18:484 - error TS2589: Type instantiation is excessively deep and possibly infinite.

18     patchState<P1 extends keyof Object.Path<S, []>, P2 extends keyof Object.Path<S, [P1]>, P3 extends keyof Object.Path<S, [P1, P2]>, P4 extends keyof Object.Path<S, [P1, P2, P3]>, P5 extends keyof Object.Path<S, [P1, P2, P3, P4]>, P6 extends keyof Object.Path<S, [P1, P2, P3, P4, P5]>, P7 extends keyof Object.Path<S, [P1, P2, P3, P4, P5, P6]>, P8 extends keyof Object.Path<S, [P1, P2, P3, P4, P5, P6, P7]>, P9 extends keyof Object.Path<S, [P1, P2, P3, P4, P5, P6, P7, P8]>>(value: Object.Path<S, [P1, P2, P3, P4, P5, P6, P7, P8, P9]>, part1: P1, part2: P2, part3: P3, part4: P4, part5: P5, part6: P6, part7: P7, part8: P8, part9: P9): void;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

As soon as I switch back to TS 4.0.x everything builds properly. So it seems you should be fine using Angular 11 with this TS Version. I also have to mention that I haven't proceeded any further and didn't upgraded/test our main application due to time constraints. So I don't know if `ng serve` will break with 4.0. But while building succeeds you should be fine.

**Comment by georgebyte** [comment]
@klopsknoedel Thanks for this elaborate response!

I did some testing myself and these are the results:

```
Angular@10.2.4 + TS@4.0.2: ✅
Angular@10.2.4 + TS@4.1.5: ❌
    ERROR in The Angular Compiler requires TypeScript >=3.9.2 and <4.1.0 but 4.1.5 was found instead.
Angular@11.2.3 + TS@4.0.2: ❌
    Compilation never finishes.
Angular@11.2.3 + TS@4.0.7: ❌
    Compilation never finishes.
Angular@11.2.3 + TS@4.1.2: ❌
    Compilation never finishes.
```

Unfortunately it seems there's currently no way to use `rxjs-observable-store` with Angular@11. 

I'm a bit surprised by the fact that Angular@10.2.4 + TS@4.0.2 combination works while Angular@11.2.3 + TS@4.0.2 doesn't. This would indicate that TS version upgrade is not the problem. It's the Angular upgrade that causes problems. I need to research this further.

**Comment by klopsknoedel** [comment]
Any news on this one? I've did some tests and I had no problems using Angular 11.x with TS 4.0.x. But as soon as I update to TS 4.1.x the build fails with the error described earlier.

**Comment by klopsknoedel** [comment]
Just a quick update. I did a test-upgrade from Angular 11.x + TS 4.0.x (which worked for us) to Angular 12.2.0 + TS 4.3.5 and still no issues. So it seems, at least for us, that only TS 4.1.x and TS 4.2.x brake rxjs-observable-store.

**Comment by georgebyte** [comment]
I finally got around to try to fix these issues again. I've published the [v3.1.0](https://github.com/georgebyte/rxjs-observable-store/releases/tag/v3.1.0) release of `rxjs-observable-store` which should take care of builds getting stuck. I've successfully build and served an Angular 13 project (`TS@4.5.5` and `rxjs@7.5.2`) when using version [v3.1.0](https://github.com/georgebyte/rxjs-observable-store/releases/tag/v3.1.0). Hopefully it works for others as well. Closing this for now.

PS: Thank you @klopsknoedel for contributing your time and debugging help!

**Comment by klopsknoedel** [comment]
Thank you for your work! Would've provided a PR if I would've known how to rewrite these type overloads to get rid of the error but it seems like the problem was somewhere else (TS, rxjs, ...).
So thanks again as a Angular@13 - Update is scheduled on our project :)
